api_scam_report/api_scam_report/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('scam-report/', include('scam_report.urls', namespace='scam_report')),
]+ static(settings.STATIC_URL)

api_scam_report/scam_report/urls.py
from django.urls import path
from scam_report import views

app_name = "scam_report"

urlpatterns = [
    path('predict/email-scam', views.predictEmailScam),
    path ('upload-file', views.upload_file, name="upload"),
]

api_scam_report/scam_report/models.py
from django.db import models

# Create your models here.

api_scam_report/scam_report/forms.py
from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField(widget=forms.FileInput(attrs={"class":"form-control"}))

api_scam_report/scam_report/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from scam_report.data_processing import email, load_email, predict_spam
from scam_report.forms import UploadFileForm
import os
from scam_report.filers import handle_uploaded_file


def upload_file(request):
    file_dir = os.path.dirname(__file__)  # get current directory
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            f = request.FILES['file']
            file_path = handle_uploaded_file(request.FILES['file'])
            data = load_email(file_path)
            result = predict_spam(result)
            # return JsonResponse({'data':file_path})
            return render(request, 'scam_report/upload.html', {'result': result, 'is_fraudulent':result[0], 'form': form})
    else:
        form = UploadFileForm()
    return render(request, 'scam_report/upload.html', {'form': form})

def predictEmailScam(request):
    """
    List all code snippets, or create a new snippet.
    """
    # http://127.0.0.1:8000/static/scam-report/file1.eml

    if request.method == 'GET':
        file_path = request.GET.get('file_path')
        module_dir = os.path.dirname(__file__)  # get current directory
        email_file = request.get('http://127.0.0.1:8000/static/scam-report/file1.eml')
        file_path = os.path.join(module_dir, 'email_messages/1.emil')
        with open("email_messages/1.eml", 'rb') as f:
            data = email.parser.BytesParser(policy=email.policy.default).parse(f)
        # data = load_email("file:///home/ajagabos007/Downloads/spam-predictor-model/api_scam_report/scam_report/email_messages/1.eml")
        result = predict_spam(data)
        print(result)
        # data = bytes(email_file.text, 'utf-8')
        # response = predict_spam("http://127.0.0.1:8000/static/scam-report/file1.eml")
        return JsonResponse({'data': "data loaded"})

    elif request.method == 'POST':
        
        return JsonResponse({'text': 'POST REQUEST RECEIVED'})

api_scam_report/scam_report/templates/scam_report/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <div class="b-example-divider"></div>

    <div class="container col-xl-10 col-xxl-8 px-4 py-5">
      <div class="row align-items-center g-lg-5 py-5">
        {% if result %}

          <div class="col-lg-12 ">
            <div class="alert {%if is_fraudulent %} alert-danger {% else %} alert-success {% endif %} alert-dismissible fade show" role="alert">
              <strong>{% if is_fraudulent %} Danger! {% else %} Good! {% endif %}</strong>  
                {%if is_fraudulent %} Fradulent Email Detected {% else %} No Fraud detected {% endif %}
                <div>
                  <strong>Result: </strong>{% for a in result %} {{a}} {% endfor %}
                </div>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          </div>
        {% endif %}
        <div class="col-lg-7 text-center text-lg-start">
          <h1 class="display-4 fw-bold lh-1 mb-3">Fradulent Email Prediction using Machine Learning</h1>
          <p class="col-lg-10 fs-4">Upload spam email file in .eml format</p>
        </div>
        <div class="col-md-10 mx-auto col-lg-5">
          
            {% if form.errors %}
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Whoops!</strong>  Something went wrong.
                      <div class="p-2">
                        {% for field in form %}
                          {{ field.errors }}
                        {% endfor %}  
                        <div class="">
                            {{form.non_field_errors}}
                        </div>                 
                    </div> 
                    <div class="">
                        {{form.non_field_errors}}
                    </div>    
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% endif %}
          <form method="POST" account ="{% url 'scam_report:upload' %}" enctype="multipart/form-data" class="p-4 p-md-5 border rounded-3 bg-light">
            {% csrf_token %}
            <div class="form-group mb-3">
                <label for="floatingInput">{{form.file.label_tag}}</label>
                {{form.file}}
              </div>
            <!-- <div class="form-floating mb-3">
              <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
              <label for="floatingInput">Email address</label>
            </div> -->
               
            <button class="w-100 btn btn-lg btn-primary" type="submit">Predict Mail Scam</button>
          </form>
        </div>
      </div>
    </div>
   
    
</body>
</html>